### ISSUE TITLE
Combile errors 

### ISSUE THREAD

**Issue by iivana** [jumakki/esphome-ensto#1]
Hi,

Got two compile errors when installing using integrated HomeAssistant ESPHome add-on (latest 2022.9.4). Didn't have yet time to dig deeper on possible fixes..

1. "/config/esphome/esphome-ensto1.yaml:548:23: error: 'round' is not a member of 'std'"

2.  "error: 'class esphome::ble_client::BLEClient' has no member named 'remote_bda'"

Related compile log entries:

/config/esphome/esphome-ensto1.yaml: In lambda function:
/config/esphome/esphome-ensto1.yaml:548:23: error: 'round' is not a member of 'std'
                       int16_t value = std::round(temperature_offset * 10);
                       ^
/config/esphome/esphome-ensto1.yaml:548:23: note: suggested alternative:
In file included from /data/cache/platformio/packages/toolchain-xtensa32/xtensa-esp32-elf/include/c++/5.2.0/cmath:44:0,
                 from /data/cache/platformio/packages/toolchain-xtensa32/xtensa-esp32-elf/include/c++/5.2.0/random:38,
                 from /data/cache/platformio/packages/toolchain-xtensa32/xtensa-esp32-elf/include/c++/5.2.0/bits/stl_algo.h:66,
                 from /data/cache/platformio/packages/toolchain-xtensa32/xtensa-esp32-elf/include/c++/5.2.0/algorithm:62,
                 from src/esphome/core/optional.h:19,
                 from src/esphome/components/socket/socket.h:6,
                 from src/esphome/components/api/api_frame_helper.h:13,
                 from src/esphome/components/api/api_connection.h:3,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
/data/cache/platformio/packages/framework-arduinoespressif32/tools/sdk/include/newlib/math.h:278:15: note:   'round'
 extern double round _PARAMS((double));
               ^
/config/esphome/esphome-ensto1.yaml: In lambda function:
/config/esphome/esphome-ensto1.yaml:570:23: error: 'round' is not a member of 'std'
                       int16_t value = std::round(boost_offset * 100);
                       ^
/config/esphome/esphome-ensto1.yaml:570:23: note: suggested alternative:
In file included from /data/cache/platformio/packages/toolchain-xtensa32/xtensa-esp32-elf/include/c++/5.2.0/cmath:44:0,
                 from /data/cache/platformio/packages/toolchain-xtensa32/xtensa-esp32-elf/include/c++/5.2.0/random:38,
                 from /data/cache/platformio/packages/toolchain-xtensa32/xtensa-esp32-elf/include/c++/5.2.0/bits/stl_algo.h:66,
                 from /data/cache/platformio/packages/toolchain-xtensa32/xtensa-esp32-elf/include/c++/5.2.0/algorithm:62,
                 from src/esphome/core/optional.h:19,
                 from src/esphome/components/socket/socket.h:6,
                 from src/esphome/components/api/api_frame_helper.h:13,
                 from src/esphome/components/api/api_connection.h:3,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
/data/cache/platformio/packages/framework-arduinoespressif32/tools/sdk/include/newlib/math.h:278:15: note:   'round'
 extern double round _PARAMS((double));
               ^
/config/esphome/esphome-ensto1.yaml: In lambda function:
/config/esphome/esphome-ensto1.yaml:81:38: error: 'class esphome::ble_client::BLEClient' has no member named 'remote_bda'
             esp_ble_set_encryption(client->remote_bda, ESP_BLE_SEC_ENCRYPT_MITM);

**Comment by jumakki** [comment]
Thanks, looks like there were breaking changes done for active connection support for Bluetooth Proxy in 2022.9.3. Should work now.

**Comment by iivana** [comment]
Works ok, that was fast. Kiitos!
