### ISSUE TITLE
Support for Ensto's own thermostat and boost function to lower temperature when nobody is home

### ISSUE THREAD

**Issue by Stembe** [jumakki/esphome-ensto#6]
Hi,

First of all, thank you for the excellent work you've already done.

I'm currently using the Ensto mobile app with the schedule function and when I know that my kids are not home, I have manually lowered the room temperature using the boost function for a set period (negative boost). Basically I have fixed boost values (-2deg / 2hrs)) that I activate when I know that the kids are not at home and in return I deactivate it when the kids come back home. Of course as the BT cannot carry 3 stories, this means that I always have to walk next to the Enstos to do this. 

I wish I could automate this function from Home Assistant as I already have the kids location known (home / away) in HA. I believe that this could be done if I would have access from Home Assistant to the boost function (on/off, target temp. and boost time) or the HA's thermostat card would use Ensto's room temperature. This function would also be very useful for lowering the inside temperature when we're not at home for awhile.

**Comment by jumakki** [comment]
Hi,

That is already possible. I improved instructions to explain how thermostats boost offset can be set. See Example 1. 

Unfortunately that doesn't work from Home Assistant directly, but you need to have ESP32 board with ESPHome and this [esphome-ensto.yaml](../blob/main/config/esphome-ensto.yaml) between Home Assistant and Ensto's thermostat to control it.
